# Generated by Django 2.2.7 on 2022-06-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=120)),
            ],
            options={
                'ordering': ['address'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_address',
            field=models.ManyToManyField(to='users.Email'),
        ),
    ]
