# Generated by Django 2.2.7 on 2022-09-26 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220618_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email_address',
            new_name='email_addresses',
        ),
        migrations.AddField(
            model_name='email',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
