# Generated by Django 2.2.7 on 2023-03-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220926_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='translate_file',
            field=models.CharField(blank=True, choices=[('English to Spanish', 'en-es')], default='', max_length=20),
        ),
    ]
