# Generated by Django 4.2 on 2023-11-11 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_my_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.JSONField(default={'notify_ebook_convert': True})),
                ('setting_ebook_convert', models.CharField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.usersettings'),
        ),
    ]
