# Generated by Django 4.2 on 2023-11-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usersettings_customuser_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User Setting', 'verbose_name_plural': 'User Settings'},
        ),
        migrations.AddField(
            model_name='email',
            name='ebook_convert',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('mobi', 'MOBI')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='setting_ebook_convert',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('mobi', 'MOBI')], default='', max_length=5),
        ),
    ]
