# Generated by Django 4.2 on 2023-12-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usersettings_customuser_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User Setting', 'verbose_name_plural': 'User Settings'},
        ),
    ]
