version: '3.7'

services:
  web:
    build: .
    command: bash -c "celery -A bookstore_project worker --loglevel=info & gunicorn bookstore_project.wsgi -b 0.0.0.0:8000 --timeout 1000"
    environment:
      - DJANGO_SETTINGS_MODULE=bookstore_project.settings
      - ENVIRONMENT=${ENVIRONMENT}
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - OPENAI_API_KEY=${OPEN_AI_KEY}
      - DEBUG=1
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq

  db:
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - 15672:15672
      - 5673:5672

volumes:
  postgres_data:
