version: '3.7'

services:
   web:
      build: .
      # command: python /code/manage.py runserver 0.0.0.0:8000
      command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
      environment:
         - DJANGO_SETTINGS_MODULE=bookstore_project.settings
         - ENVIRONMENT=development
         - SECRET_KEY=qd+g@h5h%^mc@n2ft(ac14uw=b204o=b33q!v7ri3s2j-y1c=6
         - EMAIL_HOST=smtp.gmail.com
         - EMAIL_USER=bllendev@gmail.com
         - EMAIL_PASS=ncrjjmstjcswaxtw
         - OPENAI_API_KEY=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
         - DEBUG=1
      volumes:
         - .:/code
      ports:
         - 8000:8000
      depends_on:
         - db
   db:
      image: 'postgres:12-alpine'
      environment:
           POSTGRES_PASSWORD: postgres
      volumes:
         - postgres_data:/var/lib/postgresql/data/

volumes:
   postgres_data: