version: '3.7'

services:
   web:
      build: .
      command: python /code/manage.py runserver 0.0.0.0:8000
      environment:
         - ENVIRONMENT=development
         - SECRET_KEY=qd+g@h5h%^mc@n2ft(ac14uw=b204o=b33q!v7ri3s2j-y1c=6
         - DEBUG=1
      volumes:
         - .:/code
      ports:
         - 8000:8000
      depends_on:
         - db
   db:
      image: 'postgres:12-alpine'
      environment:
           POSTGRES_PASSWORD: postgres
      volumes:
         - postgres_data:/var/lib/postgresql/data/

volumes:
   postgres_data: