# Generated by Django 4.2 on 2024-11-15 05:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='Full name of the author', max_length=255)),
                ('alias', models.CharField(blank=True, default='', help_text='Alias or pen name, if applicable', max_length=255)),
                ('birth_date', models.DateField(blank=True, help_text="Author's date of birth", null=True)),
                ('death_date', models.DateField(blank=True, help_text="Author's date of death", null=True)),
                ('webpage', models.URLField(blank=True, help_text="Link to the author's webpage or profile")),
            ],
            options={
                'verbose_name_plural': 'Authors',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='authors_aut_name_775c96_idx'),
        ),
    ]
