# Generated by Django 4.2 on 2024-11-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='author',
            name='webpage',
        ),
        migrations.AddField(
            model_name='author',
            name='alternative_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='author',
            name='key',
            field=models.CharField(blank=True, default='', help_text='The key id of the author.', max_length=255),
        ),
    ]
