# Generated by Django 2.2.7 on 2022-09-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='filetype',
            field=models.CharField(default='', max_length=60),
        ),
    ]
