# Generated by Django 2.2.7 on 2022-11-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20221113_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=200),
        ),
    ]
