# Generated by Django 2.2.7 on 2023-02-22 19:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20221117_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='link',
        ),
        migrations.AddField(
            model_name='book',
            name='json_links',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=200),
        ),
    ]
