# Generated by Django 2.2.7 on 2023-03-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20230325_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='_title_lemmatized',
            field=models.CharField(default='', max_length=500),
        ),
    ]
