# Generated by Django 4.2 on 2023-10-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_json_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='id_index',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.CharField(blank=True, default='', max_length=144),
        ),
    ]
