# Generated by Django 4.2 on 2023-11-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_book_options_remove_book_id_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-filetype', '-cover_url'], 'permissions': [('special_status', 'Can read all books')]},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
