# Generated by Django 4.2 on 2024-11-23 04:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_alter_vectorsearch_vector'),
        ('authors', '0002_remove_author_alias_remove_author_webpage_and_more'),
        ('books', '0017_alter_book_options_book_id_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='id_index',
        ),
        migrations.RemoveField(
            model_name='book',
            name='_title_lemmatized',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='filetype',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(help_text='Authors associated with the book.', related_name='books', to='authors.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the book if provided.', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbns',
            field=models.JSONField(blank=True, default=list, help_text='List of ISBNs'),
        ),
        migrations.AddField(
            model_name='book',
            name='json',
            field=models.JSONField(blank=True, default=dict, help_text='The original captured data.'),
        ),
        migrations.AddField(
            model_name='book',
            name='key',
            field=models.CharField(blank=True, help_text='Key reference to the OpenLibrary work instance.', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.CharField(blank=True, help_text='Publication date(s) in a string, formatted as needed.', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='subjects',
            field=models.JSONField(blank=True, default=list, help_text='List of subjects covered by the book.'),
        ),
        migrations.AddField(
            model_name='book',
            name='vector_search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai.vectorsearch'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, help_text="URL to the book's cover image."),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the book instance.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='json_links',
            field=models.JSONField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(blank=True, default='', help_text='The title of the book.'),
        ),
    ]
