# Generated by Django 4.2 on 2024-11-29 23:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_book_options_remove_book_id_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookGutenberg',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the book instance.', primary_key=True, serialize=False)),
                ('json', models.JSONField(blank=True, default=dict, help_text='The original captured data.')),
                ('title', models.CharField(blank=True, default='', help_text='The title of the book')),
                ('description', models.TextField(blank=True, help_text='A description of the book if provided.', null=True)),
                ('subjects', models.JSONField(blank=True, default=list, help_text='List of subjects covered by the book.')),
                ('bookshelves', models.JSONField(blank=True, default=list, help_text='List of bookshelves covered by the book.')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='json_links',
        ),
    ]
