# Generated by Django 4.2 on 2024-12-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_bookgutenberg_remove_book_json_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
