# Generated by Django 4.2 on 2024-12-02 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_alter_review_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AddField(
            model_name='book',
            name='gutenberg',
            field=models.ForeignKey(blank=True, help_text='Link to the related Gutenberg book record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.bookgutenberg'),
        ),
    ]
