# Generated by Django 4.2 on 2024-12-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_remove_book_price_book_gutenberg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgutenberg',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A description of the book if provided.'),
        ),
    ]
