# Generated by Django 4.2 on 2023-06-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
