# Generated by Django 4.2 on 2024-11-15 06:37

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_vectorsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorsearch',
            name='vector',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
