name: django - ci/cd

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Django tests
        run: |
          docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker run \
            -e DJANGO_SETTINGS_MODULE=bookstore_project.settings \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -e EMAIL_HOST=${{ secrets.EMAIL_HOST }} \
            -e EMAIL_USER=${{ secrets.EMAIL_USER }} \
            -e EMAIL_PASS=${{ secrets.EMAIL_PASS }} \
            -e OPENAI_API_KEY=${{ secrets.OPEN_AI_KEY }} \
            -e DEBUG=1 \
            -e CELERY_BROKER_URL=$CELERY_BROKER_URL \
            ghcr.io/${{ github.repository }}:${{ github.sha }} \
            python manage.py test --parallel 8 --noinput --failfast
