name: Django CI/CD

on:
  push:
    branches:
      - "*"
  pull_request_target:
    branches:
      - "*"

jobs:
  call_inherited_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/test_inherit.yml
        with:
          env_secrets: ${{ toJSON(secrets) }}
