name: Django CI/CD

on:
  push:
    branches:
      - "*"
  pull_request_target:
    branches:
      - "*"

jobs:
  call_inherited_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Test Inherited Workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"event_type": "workflow_dispatch", "client_payload": {"env_secrets": ${{ toJSON(secrets) }}}}' \
            https://api.github.com/repos/${{ github.repository }}/dispatches
