name: Django CI/CD

on:
  push:
    branches:
      - "*"
  pull_request_target:
    branches:
      - "*"

jobs:
  call_inherited_workflow:
    uses: ./.github/workflows/test_inherit.yml
    with:
      env_secrets: ${{ toJson(secrets) }}
