name: Django CI/CD

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: bookstore_project.settings
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      OPENAI_API_KEY: ${{ secrets.OPEN_AI_KEY }}
      DEBUG: 1
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5673//

    services:
      db:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pipenv
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev --deploy

    - name: Print environment variables
      run: |
        echo "SECRET_KEY: ${{ env.SECRET_KEY }}"
        echo "EMAIL_HOST: ${{ env.EMAIL_HOST }}"
        echo "EMAIL_USER: ${{ env.EMAIL_USER }}"
        echo "EMAIL_PASS: ${{ env.EMAIL_PASS }}"
        echo "OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}"
        echo "DEBUG: ${{ env.DEBUG }}"
        echo "CELERY_BROKER_URL: ${{ env.CELERY_BROKER_URL }}"

    - name: Run tests
      run: pipenv run python manage.py test --parallel --noinput --failfast
