name: Test Inherited Workflow

on:
  workflow_dispatch:
    inputs:
      env_secrets:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    environment: kalibre-bllendev
    env:
      DJANGO_SETTINGS_MODULE: bookstore_project.settings
      SECRET_KEY: ${{ fromJson(inputs.env_secrets).SECRET_KEY }}
      EMAIL_HOST: ${{ fromJson(inputs.env_secrets).EMAIL_HOST }}
      EMAIL_USER: ${{ fromJson(inputs.env_secrets).EMAIL_USER }}
      EMAIL_PASS: ${{ fromJson(inputs.env_secrets).EMAIL_PASS }}
      OPENAI_API_KEY: ${{ fromJson(inputs.env_secrets).OPEN_AI_KEY }}
      DEBUG: 1
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5673//

    services:
      db:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up secrets
      run: |
        base64 -d > lib/path/to/secrets.dart

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pipenv
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev --deploy

    - name: Run tests
      run: pipenv run python manage.py test --parallel 8 --noinput --failfast
